export type XYZ = [number, number, number];
export interface Internal { threat:number; arousal:number; nociception:number; sensitization:number; hunger:number; fatigue:number; visual_rate:number; descending_rate:number; memory_rate:number; speed_mm_s:number; behaviour:string; [key:string]:number|string; }
export interface Twin { id:string; name:string; x:number; y:number; heading:number; energy:number; spike_rate:number; spike_count:number; total_spikes:number; neural_gate:number; internal:Internal; trail:{x:number;y:number}[]; region_rates:Record<string,number>; weights:{sender:number[][];receiver:number[][];familiarity:number[]}; recognition:Record<string,number>; initial_state_hash:string; plastic_synapses:number; plastic_delta_l2:number; }
export interface Rectangle {id:string;x:number;y:number;w:number;h:number;height:number}
export interface Mouse { x:number;y:number;heading:number;speed:number;speed_mm_s:number;state:string;target:number|null;confidence:number;energy:number;attention:number;enabled:boolean;sniff_phase:number;last_seen:number[]|null;trail:{x:number;y:number}[]}
export interface World {seconds:number;width_mm:number;mouse:Mouse;obstacles:Rectangle[];refuges:Rectangle[];food:{x:number;y:number;radius:number}[];heat_zones:{x:number;y:number;radius:number;intensity:number}[];observations:Record<string,number|boolean>[];visibility_masks:{predator:boolean[];partner:boolean[];visual:boolean[]}}
export interface Protocol {id:string;title:string;hypothesis:string;control:string;measurement:string;positive:string;null:string;onset:number;offset:number;duration:number;intensity:number;elapsed?:number;}
export interface Event {id:number;tick:number;kind:string;message:string}
export interface Telemetry {tick:number;seconds:number;a:Record<string,number|boolean|string>;b:Record<string,number|boolean|string>;divergence:number;mouse_state:string}
export interface State {run_id:string;seed:number;tick:number;running:boolean;speed:number;error:string|null;mode:string;neural_ms:number;world_seconds:number;plasticity:boolean;shuffle_signals:boolean;neural_silenced:boolean;tick_wall_ms:number;twins:Twin[];world:World;experiment:Protocol;protocol:{completed:boolean};topology:Record<string,any>;metrics:Record<string,number|null>;world_history:Telemetry[];history:Record<string,any>[];events:Event[];channel:{last_trial:any;symbols:string[];confusion:number[][]};restored?:any;}
export interface AtlasData {available:boolean;nodes:{index:number;id:string;p:XYZ;region:number;cell_class:string}[];edges:[number,number,number][];regions:string[];sample:number;total:number;kind:string;}
export interface Activity {tick:number;indices:number[];a:number[];b:number[]}
export interface Checkpoint {id:string;label:string;tick:number;created:string;state_hash:string;graph_hash:string;run_id:string}
